

name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - Production

env:
  EC2_HOST: ${{ vars.EC2_HOST }}
  EC2_USER: ${{ vars.EC2_USER }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Build project
        run: npx tsc
        working-directory: backend

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd ~/test/db-assistant
            git pull origin Production
            cd backend
            npm install
            npx tsc
            pm2 restart db-server || pm2 start npx --name db-server -- ts-node server.ts
