name: Deploy Node.js to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy code to EC2
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd ${{ secrets.APP_DIR }}
          git pull origin main
          npm install
          pm2 restart myapp || pm2 start index.js --name myapp
        EOF
